import { commitFile, fetchRepoFile, triggerDeploy } from "./github.js"
import { sendTelegram, sendTelegramDocument, sendTyping } from "./telegram.js"
import { decodeGithubContent, escapeHtmlTg, jsonResponse } from "./util.js"

// ── Brain Report ─────────────────────────────────────────────────────

export function parseFrontmatterForReport(raw, filename) {
  const fmMatch = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)/)
  if (!fmMatch) return null
  const fm = fmMatch[1]
  const get = (key) => { const m = fm.match(new RegExp(`^${key}:\\s*["']?(.*?)["']?\\s*$`, 'm')); return m ? m[1].trim() : '' }
  const tagsMatch = fm.match(/^tags:\s*\[(.+?)\]/m)
  const tags = tagsMatch ? tagsMatch[1].split(',').map(t => t.trim().replace(/["']/g, '')) : []
  return { title: get('title') || filename.replace(/\.md$/, ''), date: get('date'), source: get('source') || 'manual', tags }
}

export function computeReportStats(notes) {
  const SKIP = new Set(['inbox','telegram','chat','manual','link','image','text','pdf','video','youtube','instagram','twitter','docx','note','facebook'])
  const KIND_TAGS = ['image','pdf','docx','text','video','youtube','instagram','twitter','link']
  const sources = {}, kinds = {}, topics = {}, byDay = {}
  for (const n of notes) {
    sources[n.source] = (sources[n.source] || 0) + 1
    const kind = KIND_TAGS.find(k => n.tags.includes(k)) || 'note'
    kinds[kind] = (kinds[kind] || 0) + 1
    for (const t of n.tags) { if (!SKIP.has(t)) topics[t] = (topics[t] || 0) + 1 }
    if (n.date) byDay[n.date] = (byDay[n.date] || 0) + 1
  }
  const dates = notes.map(n => n.date).filter(Boolean).sort()
  const firstDate = dates[0] || '', lastDate = dates[dates.length - 1] || ''
  const totalDays = dates.length > 1 ? Math.max(1, Math.round((new Date(lastDate) - new Date(firstDate)) / 86400000)) : 1
  const avgPerWeek = (notes.length / Math.max(1, totalDays / 7)).toFixed(1)
  const maxDay = Object.entries(byDay).sort((a, b) => b[1] - a[1])[0] || ['', 0]
  return { total: notes.length, firstDate, lastDate, totalDays, avgPerWeek, maxDay, sources, kinds, topics }
}

export async function generateReportInsights(notes, stats, env) {
  const topTopics = Object.entries(stats.topics).sort((a, b) => b[1] - a[1]).slice(0, 6).map(([t, n]) => `${t}(${n})`).join(', ')
  const titles = notes.slice(0, 25).map(n => n.title).join('; ')
  const prompt = `You are analyzing the user's personal knowledge base.

Stats: ${stats.total} notes, ${stats.firstDate} to ${stats.lastDate}. Avg ${stats.avgPerWeek}/week. Most active day: ${stats.maxDay[0]} (${stats.maxDay[1]} notes).
Top topics: ${topTopics}
Sample titles: ${titles}

Write 3-4 bullet points of genuinely insightful observations:
- What themes dominate and what they reveal about the user's focus
- Any notable patterns or shifts over time
- One concrete actionable suggestion

Be specific. No fluff. English only.`
  try {
    const r = await env.AI.run('@cf/meta/llama-3.3-70b-instruct-fp8-fast', { prompt, max_tokens: 350 })
    return (r.response || '').trim()
  } catch { return '' }
}

export function composeReportMarkdown(stats, insights, dateStr) {
  const row = (label, val) => `| ${label} | ${val} |`
  const pct = (n) => `${Math.round(n / stats.total * 100)}%`
  const topTopics = Object.entries(stats.topics).sort((a, b) => b[1] - a[1]).slice(0, 10)
  const topSources = Object.entries(stats.sources).sort((a, b) => b[1] - a[1])
  const topKinds = Object.entries(stats.kinds).sort((a, b) => b[1] - a[1])

  return `---
title: "Brain Report — ${dateStr}"
date: ${dateStr}
tags: ["report", "meta", "analysis"]
---

# 🧠 Brain Report

> Auto-generated on ${dateStr}

## Overview

| Metric | Value |
|--------|-------|
${row('Total notes', stats.total)}
${row('Period', `${stats.firstDate} → ${stats.lastDate} (${stats.totalDays} days)`)}
${row('Avg / week', stats.avgPerWeek)}
${row('Most active day', `${stats.maxDay[0]} (${stats.maxDay[1]} notes)`)}

## Sources

| Source | Notes | % |
|--------|-------|---|
${topSources.map(([s, n]) => `| ${s} | ${n} | ${pct(n)} |`).join('\n')}

## Content Types

| Type | Notes | % |
|------|-------|---|
${topKinds.map(([k, n]) => `| ${k} | ${n} | ${pct(n)} |`).join('\n')}

## Top Topics

| Tag | Count |
|-----|-------|
${topTopics.map(([t, n]) => `| #${t} | ${n} |`).join('\n')}

## 🔍 Insights

${insights || '_No insights generated._'}

---
*Generated by Second Brain Bot*
`
}

export async function generateBrainReport(env) {
  const repo = env.GITHUB_REPO || 'your-github-username/your-repo-name'
  const branch = env.GITHUB_BRANCH || 'v4'
  const ghHeaders = { Authorization: `token ${env.GITHUB_TOKEN}`, 'User-Agent': 'OrBrainBot', Accept: 'application/vnd.github.v3+json' }

  let files
  try {
    const listRes = await fetch(`https://api.github.com/repos/${repo}/contents/content/inbox?ref=${branch}`, { headers: ghHeaders })
    if (!listRes.ok) throw new Error(`GitHub list failed: ${listRes.status}`)
    files = await listRes.json()
  } catch (err) { console.error('generateBrainReport: list failed', err); return null }

  const mdFiles = Array.isArray(files) ? files.filter(f => f.type === 'file' && f.name.endsWith('.md')) : []
  if (!mdFiles.length) return null

  const noteResults = await Promise.all(
    mdFiles.map(async (file) => {
      try {
        const res = await fetch(file.url, { headers: ghHeaders })
        if (!res.ok) return null
        const data = await res.json()
        const raw = decodeGithubContent(data.content)
        return parseFrontmatterForReport(raw, file.name)
      } catch { return null }
    })
  )
  const notes = noteResults.filter(Boolean)
  if (!notes.length) return null

  const stats = computeReportStats(notes)
  const insights = await generateReportInsights(notes, stats, env)
  const dateStr = new Date().toISOString().slice(0, 10)
  const content = composeReportMarkdown(stats, insights, dateStr)
  const slug = `reports/${dateStr}-brain-report`

  try {
    await commitFile(`content/${slug}.md`, content, `report: brain analysis ${dateStr}`, env, false, false)
  } catch (err) { console.error('generateBrainReport: commit failed', err); return null }

  return { content, slug, title: `Brain Report — ${dateStr}` }
}

export async function handleReportGenerate(request, env) {
  const secret = request.headers.get('X-Chat-Passphrase')
  if (!env.CHAT_PASSPHRASE || secret !== env.CHAT_PASSPHRASE) return new Response('Unauthorized', { status: 401 })
  try {
    const result = await generateBrainReport(env)
    if (!result) return jsonResponse({ error: 'Failed to generate report' }, 500)
    const siteUrl = env.SITE_URL || 'https://your-project.pages.dev'
    await triggerDeploy(env)
    return jsonResponse({ ok: true, title: result.title, slug: result.slug, url: `${siteUrl}/${result.slug}` })
  } catch (err) {
    console.error('handleReportGenerate error:', err)
    return jsonResponse({ error: String(err) }, 500)
  }
}

export async function handleTelegramReport(message, env) {
  await sendTyping(env.TELEGRAM_BOT_TOKEN, message.chat.id)
  await sendTelegram(env.TELEGRAM_BOT_TOKEN, message.chat.id, '📊 מייצר דוח Brain…')
  try {
    const result = await generateBrainReport(env)
    if (!result) {
      await sendTelegram(env.TELEGRAM_BOT_TOKEN, message.chat.id,
        '❌ <b>לא הצלחתי לייצר דוח</b>\n\nסיבות אפשריות:\n• אין notes ב-inbox עדיין\n• בעיית גישה ל-GitHub\n\n💡 פתח Claude Code ואמור: "הפקודה /report נכשלת — עזור לאבחן"', 'HTML')
      return
    }
    const siteUrl = env.SITE_URL || 'https://your-project.pages.dev'
    const url = `${siteUrl}/${result.slug}`
    await triggerDeploy(env)
    await sendTelegram(env.TELEGRAM_BOT_TOKEN, message.chat.id,
      `📊 <b>הדוח מוכן</b>\n\n🔗 <a href="${url}">פתח דוח</a> <i>(מתפרס…)</i>`, 'HTML')
  } catch (err) {
    console.error('handleTelegramReport error:', err)
    const msg = err.message || ''
    let userMsg
    if (msg.includes('GitHub') || msg.includes('403') || msg.includes('401'))
      userMsg = '❌ <b>בעיית גישה ל-GitHub</b>\n\n💡 פתח Claude Code ואמור: "צריך לחדש את GITHUB_TOKEN של הבוט".'
    else if (msg.includes('commit'))
      userMsg = '❌ <b>הדוח נוצר אך לא נשמר</b>\n\n💡 נסה שוב. אם חוזר — פתח Claude Code ואמור "יש קונפליקט SHA בשמירת דוח".'
    else
      userMsg = `❌ <b>שגיאה ביצירת הדוח</b>\n\n<code>${escapeHtmlTg(msg.slice(0, 150))}</code>\n\n💡 העתק את ההודעה הזו ל-Claude Code לאבחון.`
    await sendTelegram(env.TELEGRAM_BOT_TOKEN, message.chat.id, userMsg, 'HTML')
  }
}

// ── Semantic Memory Profile ───────────────────────────────────────────
export async function updateMemoryProfile(env) {
  const repo = env.GITHUB_REPO || 'your-github-username/your-repo-name'
  const branch = env.GITHUB_BRANCH || 'v4'
  const ghHeaders = {
    Authorization: `token ${env.GITHUB_TOKEN}`,
    'User-Agent': 'OrBrainBot',
    Accept: 'application/vnd.github.v3+json',
  }

  let files
  try {
    const listRes = await fetch(
      `https://api.github.com/repos/${repo}/contents/content/inbox?ref=${branch}`,
      { headers: ghHeaders }
    )
    if (!listRes.ok) throw new Error(`GitHub list failed: ${listRes.status}`)
    files = await listRes.json()
  } catch (err) {
    console.error('updateMemoryProfile: failed to list notes', err)
    return null
  }

  const mdFiles = Array.isArray(files)
    ? files.filter(f => f.type === 'file' && f.name.endsWith('.md'))
    : []
  if (mdFiles.length === 0) return null

  // Slugs are timestamp-based, so reverse-alphabetical ≈ newest first
  const recent = mdFiles.sort((a, b) => b.name.localeCompare(a.name)).slice(0, 30)

  const noteTexts = await Promise.all(
    recent.map(async (file) => {
      try {
        const res = await fetch(file.url, { headers: ghHeaders })
        if (!res.ok) return null
        const data = await res.json()
        const raw = decodeGithubContent(data.content)
        const body = raw.replace(/^---[\s\S]*?---\n?/, '').trim().slice(0, 600)
        const titleMatch = raw.match(/^title:\s*["']?(.*?)["']?\s*$/m)
        const title = titleMatch ? titleMatch[1].trim() : file.name
        return `### ${title}\n${body}`
      } catch { return null }
    })
  )

  const notesContent = noteTexts.filter(Boolean).join('\n\n---\n\n')
  if (!notesContent) return null

  const prompt = `You are analyzing a personal knowledge base to build a memory profile.
Here are the ${noteTexts.filter(Boolean).length} most recent notes:

${notesContent}

Extract and return a markdown profile with these exact sections:
## Areas of Interest
## Current Focus
## Tools & Technologies
## People & Organizations
## Last Updated

Be specific and concise. Use bullet points. Write in English.
Base everything strictly on what appears in the notes — do not invent.
For "Last Updated" write today's date: ${new Date().toISOString().slice(0, 10)}`

  let profileBody
  try {
    const r = await env.AI.run('@cf/meta/llama-3.3-70b-instruct-fp8-fast', { prompt, max_tokens: 800 })
    profileBody = (r.response || '').trim()
    if (!profileBody) throw new Error('Empty LLM response')
  } catch (err) {
    console.error('updateMemoryProfile: LLM failed', err)
    return null
  }

  const fullContent = `---\ntitle: Memory Profile\ntags: ["memory", "meta"]\n---\n\n${profileBody}\n`

  try {
    await commitFile('content/memory/profile.md', fullContent, 'memory: update profile', env, false, false)
  } catch (err) {
    console.error('updateMemoryProfile: commit failed', err)
    return null
  }

  try { await env.BRAIN_KV.put('memory_profile_counter', '0') } catch {}
  console.log('updateMemoryProfile: profile updated successfully')
  return profileBody
}

export async function handleMemoryRefresh(request, env) {
  const secret = request.headers.get('X-Chat-Passphrase')
  if (!env.CHAT_PASSPHRASE || secret !== env.CHAT_PASSPHRASE) {
    return new Response('Unauthorized', { status: 401 })
  }
  const profile = await updateMemoryProfile(env)
  if (!profile) return new Response('Failed to generate profile', { status: 500 })
  return new Response(profile, { headers: { 'Content-Type': 'text/plain; charset=utf-8' } })
}

export async function handleExportCommand(message, env) {
  const chatId = message.chat.id
  const arg = (message.text || '').replace(/^\/export\s*/i, '').trim()

  await sendTelegram(env.TELEGRAM_BOT_TOKEN, chatId, '📦 מכין ייצוא...')

  try {
    if (arg) {
      // Single file: /export notes/foo or /export inbox/2026-...
      const filePath = arg.startsWith('content/') ? arg : `content/${arg}`
      const url = `https://api.github.com/repos/${env.GITHUB_REPO}/contents/${filePath}?ref=${env.GITHUB_BRANCH || 'v4'}`
      const res = await fetch(url, { headers: { Authorization: `Bearer ${env.GITHUB_TOKEN}`, 'User-Agent': 'OrBrainBot' } })
      if (!res.ok) throw new Error(`GitHub ${res.status} for ${filePath}`)
      const data = await res.json()
      const mdContent = atob(data.content.replace(/\n/g, ''))
      const filename = filePath.split('/').pop()
      await sendTelegramDocument(env.TELEGRAM_BOT_TOKEN, chatId, filename, mdContent, `📄 ${filename}`, 'text/plain')
    } else {
      // Full export: all content/**/*.md via tree API
      const treeUrl = `https://api.github.com/repos/${env.GITHUB_REPO}/git/trees/${env.GITHUB_BRANCH || 'v4'}?recursive=1`
      const treeRes = await fetch(treeUrl, { headers: { Authorization: `Bearer ${env.GITHUB_TOKEN}`, 'User-Agent': 'OrBrainBot' } })
      if (!treeRes.ok) throw new Error(`GitHub tree ${treeRes.status}`)
      const treeData = await treeRes.json()
      const mdFiles = (treeData.tree || []).filter(f => f.type === 'blob' && f.path.startsWith('content/') && f.path.endsWith('.md') && !f.path.startsWith('content/templates/'))
      const parts = []
      // Fetch in batches of 10
      for (let i = 0; i < mdFiles.length; i += 10) {
        const batch = mdFiles.slice(i, i + 10)
        const results = await Promise.all(batch.map(async f => {
          try {
            const r = await fetch(`https://api.github.com/repos/${env.GITHUB_REPO}/contents/${f.path}?ref=${env.GITHUB_BRANCH || 'v4'}`, {
              headers: { Authorization: `Bearer ${env.GITHUB_TOKEN}`, 'User-Agent': 'OrBrainBot' },
            })
            if (!r.ok) return null
            const d = await r.json()
            const text = atob(d.content.replace(/\n/g, ''))
            return `<!-- ${f.path} -->\n${text}`
          } catch { return null }
        }))
        parts.push(...results.filter(Boolean))
      }
      const dateStr = new Date().toISOString().slice(0, 10)
      const combined = parts.join('\n\n---\n\n')
      const filename = `brain-export-${dateStr}.md`
      await sendTelegramDocument(env.TELEGRAM_BOT_TOKEN, chatId, filename, combined, `📚 ${mdFiles.length} קבצים`, 'text/plain')
    }
  } catch (err) {
    console.error('handleExportCommand error:', err)
    await sendTelegram(env.TELEGRAM_BOT_TOKEN, chatId, `❌ ייצוא נכשל: ${escapeHtmlTg(err.message)}`, 'HTML')
  }
}

export async function handleStubContextReply(message, env) {
  const chatId = message.chat.id
  const contextText = (message.text || '').trim()
  if (!contextText) return

  try {
    // Get recent inbox files (last 60 min)
    const treeUrl = `https://api.github.com/repos/${env.GITHUB_REPO}/git/trees/${env.GITHUB_BRANCH || 'v4'}?recursive=1`
    const treeRes = await fetch(treeUrl, { headers: { Authorization: `Bearer ${env.GITHUB_TOKEN}`, 'User-Agent': 'OrBrainBot' } })
    if (!treeRes.ok) throw new Error(`GitHub tree ${treeRes.status}`)
    const treeData = await treeRes.json()
    const now = Date.now()
    const inboxFiles = (treeData.tree || [])
      .filter(f => f.type === 'blob' && f.path.startsWith('content/inbox/') && f.path.endsWith('.md'))
      .map(f => {
        const tsMatch = f.path.match(/content\/inbox\/(\d{4}-\d{2}-\d{2})-(\d+)\.md/)
        const ts = tsMatch ? parseInt(tsMatch[2]) : 0
        return { ...f, ts }
      })
      .filter(f => f.ts > 0 && now - f.ts < 60 * 60 * 1000)
      .sort((a, b) => b.ts - a.ts)

    if (!inboxFiles.length) {
      await sendTelegram(env.TELEGRAM_BOT_TOKEN, chatId, '⚠️ לא נמצא לינק שנשמר בשעה האחרונה')
      return
    }

    // Fetch the most recent stub
    const target = inboxFiles[0]
    const fileUrl = `https://api.github.com/repos/${env.GITHUB_REPO}/contents/${target.path}?ref=${env.GITHUB_BRANCH || 'v4'}`
    const fileRes = await fetch(fileUrl, { headers: { Authorization: `Bearer ${env.GITHUB_TOKEN}`, 'User-Agent': 'OrBrainBot' } })
    if (!fileRes.ok) throw new Error(`GitHub ${fileRes.status}`)
    const fileData = await fileRes.json()
    let existing = atob(fileData.content.replace(/\n/g, ''))

    // Add title to frontmatter if missing and append context
    if (!existing.includes('\ntitle:') && existing.startsWith('---')) {
      existing = existing.replace(/^---\n/, `---\ntitle: "${contextText.slice(0, 80)}"\n`)
    }
    if (!existing.trim().endsWith(contextText)) {
      existing = existing.trimEnd() + `\n\n${contextText}\n`
    }
    // Context arrived — clear pending-context so promote.mjs picks the file up
    existing = existing.replace(/^status: pending-context\n/m, '')

    await commitFile(target.path, existing, `inbox: add context to ${target.path.split('/').pop()}`, env, false, false)
    await sendTelegram(env.TELEGRAM_BOT_TOKEN, chatId, `✅ הוספתי את ההערה ל-<code>${target.path.split('/').pop()}</code>`, 'HTML')
  } catch (err) {
    console.error('handleStubContextReply error:', err)
    await sendTelegram(env.TELEGRAM_BOT_TOKEN, chatId, `❌ שגיאה: ${escapeHtmlTg(err.message)}`, 'HTML')
  }
}

// ── Daily digest ───────────────────────────────────────────────────────
export async function sendDailyDigest(env) {
  try {
    const chatIds = env.ALLOWED_CHAT_IDS ? env.ALLOWED_CHAT_IDS.split(',').map(s => s.trim()) : []
    if (!chatIds.length) return

    const now = new Date()
    const israelNow = new Date(now.getTime() + 3 * 3600000)
    const yesterday = new Date(israelNow)
    yesterday.setUTCDate(yesterday.getUTCDate() - 1)
    const yStr = yesterday.toISOString().split('T')[0] // YYYY-MM-DD

    // Fetch yesterday's notes from GitHub
    const branch = env.GITHUB_BRANCH || 'v4'
    const treeRes = await fetch(
      `https://api.github.com/repos/${env.GITHUB_REPO}/git/trees/HEAD?recursive=1`,
      { headers: { Authorization: `Bearer ${env.GITHUB_TOKEN}`, 'User-Agent': 'OrBrainBot' } }
    )
    const treeData = treeRes.ok ? await treeRes.json() : null
    const yesterdayFiles = (treeData?.tree || [])
      .filter(f => f.path.startsWith('content/inbox/') && f.path.includes(yStr) && f.path.endsWith('.md'))
      .slice(0, 10)

    // Fetch today's reminders
    const reminderList = await env.BRAIN_KV.list({ prefix: 'reminder:' })
    const todayStart = new Date(israelNow)
    todayStart.setUTCHours(0, 0, 0, 0)
    const todayEnd = new Date(todayStart.getTime() + 86400000)
    const todayReminders = []
    for (const key of reminderList.keys) {
      const [, tsStr] = key.name.split(':')
      const ts = parseInt(tsStr, 10)
      if (ts >= todayStart.getTime() && ts < todayEnd.getTime()) {
        const val = await env.BRAIN_KV.get(key.name, 'json')
        if (val) todayReminders.push(val)
      }
    }

    // Check if any chatId has a read-later queue (don't skip digest if queue is non-empty)
    let anyQueueItems = false
    if (!yesterdayFiles.length && !todayReminders.length) {
      for (const chatId of chatIds) {
        const q = await env.BRAIN_KV.list({ prefix: `readlater:${chatId}:` }).catch(() => ({ keys: [] }))
        if (q.keys.length) { anyQueueItems = true; break }
      }
      if (!anyQueueItems) return
    }

    const lines = [`☀️ *בוקר טוב!*`] // TODO: personalize with your own name if you want

    if (yesterdayFiles.length) {
      lines.push('', `📥 *נשמר אתמול (${yesterdayFiles.length} פריטים):*`)
      const siteUrl = env.SITE_URL || 'https://your-project.pages.dev'
      // Fetch real titles from each file's frontmatter (parallel)
      const previews = await Promise.all(yesterdayFiles.slice(0, 5).map(async (f) => {
        const slug = f.path.replace('content/', '').replace('.md', '')
        try {
          const res = await fetch(
            `https://api.github.com/repos/${env.GITHUB_REPO}/contents/${f.path}?ref=${branch}`,
            { headers: { Authorization: `Bearer ${env.GITHUB_TOKEN}`, 'User-Agent': 'OrBrainBot' } }
          )
          if (!res.ok) return { slug, title: slug }
          const data = await res.json()
          const md = decodeGithubContent(data.content) || ''
          // Parse title from frontmatter
          const fmMatch = md.match(/^---\s*\n([\s\S]*?)\n---/)
          let title = ''
          if (fmMatch) {
            const titleLine = fmMatch[1].match(/^title:\s*["']?(.+?)["']?\s*$/m)
            if (titleLine) title = titleLine[1].trim()
          }
          // Fallback: first non-frontmatter, non-blockquote line
          if (!title) {
            const body = md.replace(/^---[\s\S]*?\n---\n?/, '').trim()
            const firstLine = body.split('\n').map(l => l.trim()).find(l => l && !l.startsWith('>') && !l.startsWith('#'))
            if (firstLine) title = firstLine.slice(0, 60).replace(/[*_`\[\]]/g, '')
          }
          return { slug, title: title || slug }
        } catch {
          return { slug, title: slug }
        }
      }))
      for (const { slug, title } of previews) {
        lines.push(`  • [${title}](${siteUrl}/${slug})`)
      }
      if (yesterdayFiles.length > 5) lines.push(`  _...ועוד ${yesterdayFiles.length - 5} פריטים_`)
    }

    if (todayReminders.length) {
      lines.push('', `⏰ *תזכורות להיום:*`)
      todayReminders
        .sort((a, b) => new Date(a.scheduledAt) - new Date(b.scheduledAt))
        .forEach(r => {
          const t = new Date(r.scheduledAt).toLocaleTimeString('he-IL', { hour: '2-digit', minute: '2-digit', timeZone: 'Asia/Jerusalem' })
          lines.push(`  • ${t} — ${r.message}`)
        })
    }

    for (const chatId of chatIds) {
      const queueList = await env.BRAIN_KV.list({ prefix: `readlater:${chatId}:` }).catch(() => ({ keys: [] }))
      const queueCount = queueList.keys.length
      const perChat = queueCount
        ? [...lines, '', `📋 *${queueCount} פריט${queueCount !== 1 ? 'ים' : ''} בתור הקריאה — שלח /queue לעיבוד*`]
        : lines
      await sendTelegram(env.TELEGRAM_BOT_TOKEN, chatId, perChat.join('\n'), 'Markdown')
    }
  } catch (err) {
    console.error('sendDailyDigest error:', err)
  }
}

export function fmField(raw, field) {
  const m = raw.match(new RegExp(`^${field}:\\s*["']?(.+?)["']?\\s*$`, 'm'))
  return m?.[1]?.trim() || ''
}

export const WIKI_PATH_RE = /^content\/(notes|projects|meetings|decisions)\/.+\.md$/

export async function sendWeeklyReview(env) {
  try {
    const chatIds = env.ALLOWED_CHAT_IDS ? env.ALLOWED_CHAT_IDS.split(',').map(s => s.trim()) : []
    if (!chatIds.length) return
    const now = new Date()
    const israelNow = new Date(now.getTime() + 3 * 3600000)
    const dates = []
    for (let i = 1; i <= 7; i++) {
      const d = new Date(israelNow)
      d.setUTCDate(d.getUTCDate() - i)
      dates.push(d.toISOString().split('T')[0])
    }
    const treeRes = await fetch(
      `https://api.github.com/repos/${env.GITHUB_REPO}/git/trees/HEAD?recursive=1`,
      { headers: { Authorization: `Bearer ${env.GITHUB_TOKEN}`, 'User-Agent': 'OrBrainBot' } }
    )
    const treeData = treeRes.ok ? await treeRes.json() : null
    const tree = treeData?.tree || []
    const weekFiles = tree.filter(f =>
      f.path.startsWith('content/inbox/') && f.path.endsWith('.md') &&
      dates.some(d => f.path.includes(d))
    )

    // Pending-context stubs: links saved without context, waiting for a reply.
    // Filename starts with the capture date, so scan only the last 30 days of inbox files.
    const cutoff = new Date(israelNow)
    cutoff.setUTCDate(cutoff.getUTCDate() - 30)
    const cutoffStr = cutoff.toISOString().split('T')[0]
    const recentInbox = tree.filter(f => {
      if (!f.path.startsWith('content/inbox/') || !f.path.endsWith('.md')) return false
      const datePart = f.path.replace('content/inbox/', '').slice(0, 10)
      return datePart >= cutoffStr
    })
    const pendingStubs = (await Promise.all(
      recentInbox.map(async f => {
        const raw = await fetchRepoFile(f.path, env)
        if (!/^status:\s*pending-context\s*$/m.test(raw)) return null
        const source = fmField(raw, 'source')
        return { slug: f.path.replace('content/', '').replace('.md', ''), source }
      })
    )).filter(Boolean)

    // Wiki pages created or updated this week (frontmatter date/updated)
    const wikiFiles = tree.filter(f => WIKI_PATH_RE.test(f.path))
    const wikiChanged = (await Promise.all(
      wikiFiles.map(async f => {
        const raw = await fetchRepoFile(f.path, env)
        if (!raw) return null
        const updated = fmField(raw, 'updated') || fmField(raw, 'date')
        if (!dates.includes(updated)) return null
        return { slug: f.path.replace('content/', '').replace('.md', ''), title: fmField(raw, 'title') }
      })
    )).filter(Boolean)

    // Resurface one note from the archive: oldest `updated`, untouched for 21+ days
    const resurfaceCutoff = new Date(israelNow)
    resurfaceCutoff.setUTCDate(resurfaceCutoff.getUTCDate() - 21)
    const resurfaceCutoffStr = resurfaceCutoff.toISOString().split('T')[0]
    let resurfaced = null
    const noteFiles = tree.filter(f => /^content\/notes\/.+\.md$/.test(f.path))
    if (noteFiles.length) {
      const candidates = (await Promise.all(
        noteFiles.map(async f => {
          const raw = await fetchRepoFile(f.path, env)
          if (!raw) return null
          const updated = fmField(raw, 'updated') || fmField(raw, 'date')
          if (!updated || updated > resurfaceCutoffStr) return null
          return { slug: f.path.replace('content/', '').replace('.md', ''), title: fmField(raw, 'title'), updated }
        })
      )).filter(Boolean)
      if (candidates.length) resurfaced = candidates[Math.floor(Math.random() * candidates.length)]
    }

    const siteUrl = env.SITE_URL || 'https://your-project.pages.dev'
    const weekStart = dates[6], weekEnd = dates[0]
    const lines = [
      `📅 <b>סיכום שבועי</b>`,
      `<i>${weekStart} — ${weekEnd}</i>`,
      '',
      `📥 נשמרו <b>${weekFiles.length}</b> פריטים השבוע`,
    ]

    if (weekFiles.length) {
      const noteTexts = await Promise.all(
        weekFiles.slice(0, 20).map(async (file) => {
          const raw = await fetchRepoFile(file.path, env)
          if (!raw) return null
          const title = fmField(raw, 'title') || file.path.split('/').pop()?.replace('.md', '')
          const summary = fmField(raw, 'summary')
          return `- ${title}${summary ? ': ' + summary.slice(0, 100) : ''}`
        })
      )
      const noteList = noteTexts.filter(Boolean).join('\n')
      if (noteList) {
        const prompt = `You are the user's personal assistant. Here are the ${noteTexts.filter(Boolean).length} notes the user saved this week:\n\n${noteList}\n\nWrite a short weekly review in Hebrew (3-5 bullet points):\n• What main themes emerged this week\n• Interesting patterns or connections between topics\n• One suggested follow-up or action\n\nBe specific and personal. No fluff. Under 200 words.`
        const r = await env.AI.run('@cf/meta/llama-3.3-70b-instruct-fp8-fast', { prompt, max_tokens: 400 })
        const insights = (r.response || '').trim()
        if (insights) lines.push('', escapeHtmlTg(insights))
      }
    }

    if (wikiChanged.length) {
      lines.push('', `🧠 <b>הוויקי גדל:</b> ${wikiChanged.length} עמודים נוצרו/עודכנו`)
      for (const w of wikiChanged.slice(0, 5)) {
        lines.push(`  • <a href="${siteUrl}/${w.slug}">${escapeHtmlTg(w.title || w.slug)}</a>`)
      }
    }

    if (pendingStubs.length) {
      lines.push('', `🕗 <b>${pendingStubs.length} לינקים מחכים להקשר:</b>`)
      for (const s of pendingStubs.slice(0, 5)) {
        lines.push(`  • ${escapeHtmlTg(s.source || s.slug)}`)
      }
      lines.push(`  <i>שלח כמה מילים על כל אחד ואתייק אותם</i>`)
    }

    if (resurfaced) {
      lines.push('', `🔄 <b>מהארכיון:</b> <a href="${siteUrl}/${resurfaced.slug}">${escapeHtmlTg(resurfaced.title || resurfaced.slug)}</a> (לא נגעת בו מאז ${resurfaced.updated}) — עדיין רלוונטי?`)
    }

    // Synthesis opportunities from the latest lint report (missing-pages section)
    const lintFiles = tree
      .filter(f => /^content\/lint\/\d{4}-\d{2}-\d{2}\.md$/.test(f.path))
      .map(f => f.path)
      .sort()
    if (lintFiles.length) {
      const lintRaw = await fetchRepoFile(lintFiles[lintFiles.length - 1], env)
      const sectionM = lintRaw.match(/^#+.*(missing|חסר)[^\n]*\n([\s\S]*?)(?=\n#+|\n*$)/im)
      const bullets = (sectionM?.[2] || '')
        .split('\n')
        .filter(l => /^\s*[-*]/.test(l))
        .slice(0, 3)
        .map(l => l.replace(/^\s*[-*]\s*/, '').trim())
        .filter(Boolean)
      if (bullets.length) {
        lines.push('', `🧩 <b>הזדמנויות סינתזה</b> (מתוך ה-lint האחרון):`)
        for (const b of bullets) lines.push(`  • ${escapeHtmlTg(b.slice(0, 120))}`)
        lines.push(`  <i>השב "תבנה עמוד על X" ואטפל בזה</i>`)
      }
    }

    lines.push('', `📝 קיבלת השבוע החלטה ששווה לתעד? כתוב אותה כאן ואתייק אותה כ-decision.`)
    lines.push('', `🔗 <a href="${siteUrl}">פתח את המוח</a>`)
    for (const chatId of chatIds)
      await sendTelegram(env.TELEGRAM_BOT_TOKEN, chatId, lines.join('\n'), 'HTML')
  } catch (err) {
    console.error('sendWeeklyReview error:', err)
  }
}